import type { ItemDefinition } from "./types";

export const itemDefinitions: Record<string, ItemDefinition> = {
  // Weapons - Common
  sword_1: {
    id: "sword_1",
    name: "Rusty Sword",
    type: "weapon",
    rarity: "common",
    stats: { attack: 5 },
    sellPrice: 50,
  },
  // Weapons - Rare
  hammer_1: {
    id: "hammer_1",
    name: "Iron Hammer",
    type: "weapon",
    rarity: "rare",
    stats: { attack: 16, defense: 4 },
    sellPrice: 75,
  },
  storm_blade: {
    id: "storm_blade",
    name: "Storm Blade",
    type: "weapon",
    rarity: "rare",
    stats: { attack: 22, agility: 6, critChance: 4 },
    sellPrice: 140,
  },
  // Weapons - Epic
  greataxe_1: {
    id: "greataxe_1",
    name: "Great Axe",
    type: "weapon",
    rarity: "epic",
    stats: { attack: 85, defense: 18, critChance: 8 },
    sellPrice: 200,
  },
  sunlance: {
    id: "sunlance",
    name: "Sunlance",
    type: "weapon",
    rarity: "epic",
    stats: { attack: 96, intelligence: 52, critChance: 10 },
    sellPrice: 320,
  },
  // Weapons - Legendary
  excalibur: {
    id: "excalibur",
    name: "Excalibur",
    type: "weapon",
    rarity: "legendary",
    stats: { attack: 2200, critChance: 42, agility: 70 },
    sellPrice: 500,
  },
  titan_cleaver: {
    id: "titan_cleaver",
    name: "Titan Cleaver",
    type: "weapon",
    rarity: "legendary",
    stats: { attack: 2800, hp: 1200, defense: 340 },
    sellPrice: 900,
  },
  astral_halberd: {
    id: "astral_halberd",
    name: "Astral Halberd",
    type: "weapon",
    rarity: "legendary",
    stats: { attack: 2600, intelligence: 850, critChance: 55 },
    sellPrice: 940,
  },
  // Weapons - Unique
  soul_edge: {
    id: "soul_edge",
    name: "Voidborn Fang",
    type: "weapon",
    rarity: "unique",
    setId: "voidborn",
    stats: { attack: 125000, intelligence: 34000, critChance: 180 },
    sellPrice: 750,
  },
  starforged_maul: {
    id: "starforged_maul",
    name: "Arcaneforge Maul",
    type: "weapon",
    rarity: "unique",
    setId: "arcaneforge",
    stats: { attack: 118000, intelligence: 46000, energyRegeneration: 220 },
    sellPrice: 1800,
  },
  worldroot_scythe: {
    id: "worldroot_scythe",
    name: "Verdant Scythe",
    type: "weapon",
    rarity: "unique",
    setId: "verdant",
    stats: { attack: 98000, plantGrowth: 260, wateringDuration: 180 },
    sellPrice: 1750,
  },
  ravenous_fang: {
    id: "ravenous_fang",
    name: "Beastlord Fang",
    type: "weapon",
    rarity: "unique",
    setId: "beastlord",
    stats: { attack: 132000, agility: 420, critChance: 210 },
    sellPrice: 1900,
  },
  bloodletter_blade: {
    id: "bloodletter_blade",
    name: "Bloodletter Blade",
    type: "weapon",
    rarity: "unique",
    setId: "bloodletter",
    stats: { attack: 128000, agility: 380, intelligence: 18000 },
    sellPrice: 1920,
  },
  windrazor_blade: {
    id: "windrazor_blade",
    name: "Windrazor Blade",
    type: "weapon",
    rarity: "unique",
    setId: "windrazor",
    stats: { attack: 116000, agility: 740, critChance: 80 },
    sellPrice: 1940,
  },
  gorelord_cleaver: {
    id: "gorelord_cleaver",
    name: "Gorelord Cleaver",
    type: "weapon",
    rarity: "unique",
    setId: "gorelord",
    stats: { attack: 196000, hp: 80000, critChance: 320 },
    sellPrice: 2420,
  },
  nightstar_staff: {
    id: "nightstar_staff",
    name: "Nightstar Staff",
    type: "weapon",
    rarity: "unique",
    setId: "nightstar",
    stats: { attack: 172000, intelligence: 132000, energyRegeneration: 880 },
    sellPrice: 2440,
  },
  rootcrown_reaper: {
    id: "rootcrown_reaper",
    name: "Rootcrown Reaper",
    type: "weapon",
    rarity: "unique",
    setId: "rootcrown",
    stats: { attack: 164000, plantGrowth: 1600, wateringDuration: 1200 },
    sellPrice: 2460,
  },
  skyhunter_bow: {
    id: "skyhunter_bow",
    name: "Skyhunter Bow",
    type: "weapon",
    rarity: "unique",
    setId: "skyhunter",
    stats: { attack: 188000, agility: 1600, critChance: 320 },
    sellPrice: 2480,
  },
  epochveil_scepter: {
    id: "epochveil_scepter",
    name: "Epochveil Scepter",
    type: "weapon",
    rarity: "unique",
    setId: "epochveil",
    stats: { attack: 170000, goldIncome: 1800, energyRegeneration: 780 },
    sellPrice: 2500,
  },
  moonpack_spear: {
    id: "moonpack_spear",
    name: "Moonpack Spear",
    type: "weapon",
    rarity: "unique",
    setId: "moonpack",
    stats: { attack: 190000, petStrength: 1800, agility: 980 },
    sellPrice: 2520,
  },

  // Armor - Common
  armor_1: {
    id: "armor_1",
    name: "Cloth Armor",
    type: "armor",
    rarity: "common",
    stats: { defense: 3 },
    sellPrice: 40,
  },
  // Armor - Rare
  shield_1: {
    id: "shield_1",
    name: "Wooden Shield",
    type: "armor",
    rarity: "rare",
    stats: { defense: 18, hp: 90 },
    sellPrice: 60,
  },
  chainmail_aegis: {
    id: "chainmail_aegis",
    name: "Chainmail Aegis",
    type: "armor",
    rarity: "rare",
    stats: { defense: 24, hp: 140, attack: 6 },
    sellPrice: 130,
  },
  // Armor - Epic
  plate_armor: {
    id: "plate_armor",
    name: "Plate Armor",
    type: "armor",
    rarity: "epic",
    stats: { defense: 95, hp: 420, attack: 26 },
    sellPrice: 250,
  },
  runesteel_plate: {
    id: "runesteel_plate",
    name: "Runesteel Plate",
    type: "armor",
    rarity: "epic",
    stats: { defense: 120, hp: 560, intelligence: 48 },
    sellPrice: 350,
  },
  // Armor - Legendary
  excalibur_armor: {
    id: "excalibur_armor",
    name: "Holy Plate Mail",
    type: "armor",
    rarity: "legendary",
    stats: { defense: 2100, hp: 9800, intelligence: 420 },
    sellPrice: 450,
  },
  aegis_of_ages: {
    id: "aegis_of_ages",
    name: "Aegis of Ages",
    type: "armor",
    rarity: "legendary",
    stats: { defense: 2600, hp: 12000, attack: 400 },
    sellPrice: 920,
  },
  celestial_bulwark: {
    id: "celestial_bulwark",
    name: "Celestial Bulwark",
    type: "armor",
    rarity: "legendary",
    stats: { defense: 2400, hp: 10400, energyRegeneration: 140 },
    sellPrice: 940,
  },
  // Armor - Unique
  void_armor: {
    id: "void_armor",
    name: "Voidborn Plate",
    type: "armor",
    rarity: "unique",
    setId: "voidborn",
    stats: { defense: 76000, hp: 260000, intelligence: 36000 },
    sellPrice: 800,
  },
  chrono_bastion: {
    id: "chrono_bastion",
    name: "Arcaneforge Bastion",
    type: "armor",
    rarity: "unique",
    setId: "arcaneforge",
    stats: { defense: 68000, hp: 240000, energyRegeneration: 420 },
    sellPrice: 1760,
  },
  nightweave_carapace: {
    id: "nightweave_carapace",
    name: "Verdant Carapace",
    type: "armor",
    rarity: "unique",
    setId: "verdant",
    stats: { defense: 64000, hp: 220000, plantGrowth: 360 },
    sellPrice: 1740,
  },
  predator_mail: {
    id: "predator_mail",
    name: "Beastlord Mail",
    type: "armor",
    rarity: "unique",
    setId: "beastlord",
    stats: { defense: 82000, hp: 280000, agility: 420 },
    sellPrice: 1880,
  },
  bloodletter_garb: {
    id: "bloodletter_garb",
    name: "Bloodletter Garb",
    type: "armor",
    rarity: "unique",
    setId: "bloodletter",
    stats: { defense: 70000, hp: 250000, agility: 440, attack: 46000 },
    sellPrice: 1890,
  },
  windrazor_mail: {
    id: "windrazor_mail",
    name: "Windrazor Mail",
    type: "armor",
    rarity: "unique",
    setId: "windrazor",
    stats: { defense: 64000, hp: 230000, agility: 680, attack: 38000 },
    sellPrice: 1910,
  },
  gorelord_plate: {
    id: "gorelord_plate",
    name: "Gorelord Plate",
    type: "armor",
    rarity: "unique",
    setId: "gorelord",
    stats: { defense: 98000, hp: 520000, attack: 88000 },
    sellPrice: 2420,
  },
  nightstar_veil: {
    id: "nightstar_veil",
    name: "Nightstar Veil",
    type: "armor",
    rarity: "unique",
    setId: "nightstar",
    stats: { defense: 84000, hp: 460000, intelligence: 180000 },
    sellPrice: 2440,
  },
  rootcrown_barkmail: {
    id: "rootcrown_barkmail",
    name: "Rootcrown Barkmail",
    type: "armor",
    rarity: "unique",
    setId: "rootcrown",
    stats: { defense: 88000, hp: 560000, plantGrowth: 1400 },
    sellPrice: 2460,
  },
  skyhunter_mail: {
    id: "skyhunter_mail",
    name: "Skyhunter Mail",
    type: "armor",
    rarity: "unique",
    setId: "skyhunter",
    stats: { defense: 90000, hp: 500000, agility: 1500, critChance: 210 },
    sellPrice: 2480,
  },
  epochveil_coat: {
    id: "epochveil_coat",
    name: "Epochveil Coat",
    type: "armor",
    rarity: "unique",
    setId: "epochveil",
    stats: { defense: 86000, hp: 490000, goldIncome: 1600 },
    sellPrice: 2500,
  },
  moonpack_mail: {
    id: "moonpack_mail",
    name: "Moonpack Mail",
    type: "armor",
    rarity: "unique",
    setId: "moonpack",
    stats: { defense: 94000, hp: 600000, petStrength: 1500 },
    sellPrice: 2520,
  },

  // Accessories - Common
  ring_1: {
    id: "ring_1",
    name: "Old Ring",
    type: "accessory",
    rarity: "common",
    stats: { attack: 1 },
    sellPrice: 30,
  },
  // Accessories - Rare
  amulet_1: {
    id: "amulet_1",
    name: "Crystal Amulet",
    type: "accessory",
    rarity: "rare",
    stats: { intelligence: 14, attack: 6, critChance: 3 },
    sellPrice: 100,
  },
  battle_charm: {
    id: "battle_charm",
    name: "Battle Charm",
    type: "accessory",
    rarity: "rare",
    stats: { attack: 16, critChance: 8, agility: 10 },
    sellPrice: 150,
  },
  // Accessories - Epic
  dragon_ring: {
    id: "dragon_ring",
    name: "Dragon Ring",
    type: "accessory",
    rarity: "epic",
    stats: { attack: 70, defense: 42, critChance: 12 },
    sellPrice: 180,
  },
  mindspire_talisman: {
    id: "mindspire_talisman",
    name: "Mindspire Talisman",
    type: "accessory",
    rarity: "epic",
    stats: { attack: 62, intelligence: 110, energyRegeneration: 40 },
    sellPrice: 310,
  },
  // Accessories - Legendary
  infinity_gem: {
    id: "infinity_gem",
    name: "Infinity Gem",
    type: "accessory",
    rarity: "legendary",
    stats: { attack: 1900, defense: 980, intelligence: 1800, critChance: 48 },
    sellPrice: 400,
  },
  sovereign_signet: {
    id: "sovereign_signet",
    name: "Sovereign Signet",
    type: "accessory",
    rarity: "legendary",
    stats: { attack: 2100, goldIncome: 160, critChance: 52 },
    sellPrice: 920,
  },
  comet_locket: {
    id: "comet_locket",
    name: "Comet Locket",
    type: "accessory",
    rarity: "legendary",
    stats: { intelligence: 2200, energyRegeneration: 180, attack: 1400 },
    sellPrice: 930,
  },
  // Accessories - Unique
  chaos_emerald: {
    id: "chaos_emerald",
    name: "Voidborn Sigil",
    type: "accessory",
    rarity: "unique",
    setId: "voidborn",
    stats: { attack: 88000, intelligence: 70000, critChance: 210 },
    sellPrice: 600,
  },
  eclipse_prism: {
    id: "eclipse_prism",
    name: "Arcaneforge Prism",
    type: "accessory",
    rarity: "unique",
    setId: "arcaneforge",
    stats: { attack: 76000, intelligence: 92000, energyRegeneration: 420 },
    sellPrice: 1700,
  },
  worldheart_orb: {
    id: "worldheart_orb",
    name: "Verdant Orb",
    type: "accessory",
    rarity: "unique",
    setId: "verdant",
    stats: { attack: 65000, goldIncome: 480, plantGrowth: 420 },
    sellPrice: 1680,
  },
  warpack_totem: {
    id: "warpack_totem",
    name: "Beastlord Totem",
    type: "accessory",
    rarity: "unique",
    setId: "beastlord",
    stats: { attack: 94000, agility: 520, petStrength: 280 },
    sellPrice: 1860,
  },
  bloodmark_charm: {
    id: "bloodmark_charm",
    name: "Bloodmark Charm",
    type: "accessory",
    rarity: "unique",
    setId: "bloodletter",
    stats: { attack: 91000, agility: 360, critChance: 120 },
    sellPrice: 1870,
  },
  windrazor_charm: {
    id: "windrazor_charm",
    name: "Windrazor Charm",
    type: "accessory",
    rarity: "unique",
    setId: "windrazor",
    stats: { attack: 86000, agility: 620, critChance: 90 },
    sellPrice: 1890,
  },
  voidborn_core: {
    id: "voidborn_core",
    name: "Voidborn Core",
    type: "accessory",
    rarity: "unique",
    setId: "voidborn",
    stats: { attack: 104000, intelligence: 94000, energyRegeneration: 820 },
    sellPrice: 1950,
  },
  arcaneforge_seal: {
    id: "arcaneforge_seal",
    name: "Arcaneforge Seal",
    type: "accessory",
    rarity: "unique",
    setId: "arcaneforge",
    stats: { attack: 92000, intelligence: 124000, energyRegeneration: 900 },
    sellPrice: 1970,
  },
  verdant_heart: {
    id: "verdant_heart",
    name: "Verdant Heart",
    type: "accessory",
    rarity: "unique",
    setId: "verdant",
    stats: { attack: 78000, plantGrowth: 1200, wateringDuration: 980 },
    sellPrice: 1990,
  },
  beastlord_fetish: {
    id: "beastlord_fetish",
    name: "Beastlord Fetish",
    type: "accessory",
    rarity: "unique",
    setId: "beastlord",
    stats: { attack: 108000, petStrength: 980, agility: 760 },
    sellPrice: 2010,
  },
  bloodletter_emblem: {
    id: "bloodletter_emblem",
    name: "Bloodletter Emblem",
    type: "accessory",
    rarity: "unique",
    setId: "bloodletter",
    stats: { attack: 112000, critChance: 220, agility: 720 },
    sellPrice: 2030,
  },
  windrazor_emblem: {
    id: "windrazor_emblem",
    name: "Windrazor Emblem",
    type: "accessory",
    rarity: "unique",
    setId: "windrazor",
    stats: { attack: 106000, agility: 980, critChance: 180 },
    sellPrice: 2050,
  },
  gorelord_charm: {
    id: "gorelord_charm",
    name: "Gorelord Charm",
    type: "accessory",
    rarity: "unique",
    setId: "gorelord",
    stats: { attack: 128000, hp: 160000, critChance: 300 },
    sellPrice: 2420,
  },
  gorelord_emblem: {
    id: "gorelord_emblem",
    name: "Gorelord Emblem",
    type: "accessory",
    rarity: "unique",
    setId: "gorelord",
    stats: { attack: 132000, hp: 180000, agility: 900 },
    sellPrice: 2430,
  },
  nightstar_prism: {
    id: "nightstar_prism",
    name: "Nightstar Prism",
    type: "accessory",
    rarity: "unique",
    setId: "nightstar",
    stats: { attack: 114000, intelligence: 180000, energyRegeneration: 980 },
    sellPrice: 2440,
  },
  nightstar_seal: {
    id: "nightstar_seal",
    name: "Nightstar Seal",
    type: "accessory",
    rarity: "unique",
    setId: "nightstar",
    stats: { attack: 118000, intelligence: 190000, critChance: 260 },
    sellPrice: 2450,
  },
  rootcrown_talisman: {
    id: "rootcrown_talisman",
    name: "Rootcrown Talisman",
    type: "accessory",
    rarity: "unique",
    setId: "rootcrown",
    stats: { attack: 108000, plantGrowth: 1800, wateringDuration: 1200 },
    sellPrice: 2460,
  },
  rootcrown_mark: {
    id: "rootcrown_mark",
    name: "Rootcrown Mark",
    type: "accessory",
    rarity: "unique",
    setId: "rootcrown",
    stats: { attack: 112000, plantGrowth: 1900, hp: 160000 },
    sellPrice: 2470,
  },
  skyhunter_charm: {
    id: "skyhunter_charm",
    name: "Skyhunter Charm",
    type: "accessory",
    rarity: "unique",
    setId: "skyhunter",
    stats: { attack: 122000, agility: 1800, critChance: 240 },
    sellPrice: 2480,
  },
  skyhunter_signet: {
    id: "skyhunter_signet",
    name: "Skyhunter Signet",
    type: "accessory",
    rarity: "unique",
    setId: "skyhunter",
    stats: { attack: 126000, agility: 1900, critChance: 280 },
    sellPrice: 2490,
  },
  epochveil_charm: {
    id: "epochveil_charm",
    name: "Epochveil Charm",
    type: "accessory",
    rarity: "unique",
    setId: "epochveil",
    stats: { attack: 116000, goldIncome: 2600, energyRegeneration: 960 },
    sellPrice: 2500,
  },
  epochveil_signet: {
    id: "epochveil_signet",
    name: "Epochveil Signet",
    type: "accessory",
    rarity: "unique",
    setId: "epochveil",
    stats: { attack: 120000, goldIncome: 3000, hp: 140000 },
    sellPrice: 2510,
  },
  moonpack_totem: {
    id: "moonpack_totem",
    name: "Moonpack Totem",
    type: "accessory",
    rarity: "unique",
    setId: "moonpack",
    stats: { attack: 124000, petStrength: 1800, agility: 1200 },
    sellPrice: 2520,
  },
  moonpack_emblem: {
    id: "moonpack_emblem",
    name: "Moonpack Emblem",
    type: "accessory",
    rarity: "unique",
    setId: "moonpack",
    stats: { attack: 128000, petStrength: 2000, critChance: 260 },
    sellPrice: 2530,
  },

  // Tools - Common
  pickaxe_1: {
    id: "pickaxe_1",
    name: "Stone Pickaxe",
    type: "tool",
    rarity: "common",
    stats: { attack: 2 },
    sellPrice: 30,
  },
  // Tools - Rare
  iron_pickaxe: {
    id: "iron_pickaxe",
    name: "Iron Pickaxe",
    type: "tool",
    rarity: "rare",
    stats: { attack: 5 },
    sellPrice: 80,
  },
  // Tools - Epic
  mithril_pickaxe: {
    id: "mithril_pickaxe",
    name: "Mithril Pickaxe",
    type: "tool",
    rarity: "epic",
    stats: { attack: 10 },
    sellPrice: 220,
  },
  shovel_1: {
    id: "shovel_1",
    name: "Garden Shovel",
    type: "tool",
    rarity: "common",
    stats: { attack: 1 },
    sellPrice: 30,
  },
  iron_shovel: {
    id: "iron_shovel",
    name: "Iron Shovel",
    type: "tool",
    rarity: "rare",
    stats: { attack: 3 },
    sellPrice: 90,
  },
  mithril_shovel: {
    id: "mithril_shovel",
    name: "Mithril Shovel",
    type: "tool",
    rarity: "epic",
    stats: { attack: 6 },
    sellPrice: 240,
  },

  // Watering Cans
  wateringcan_common: {
    id: "wateringcan_common",
    name: "Watering Can",
    type: "tool",
    rarity: "common",
    stats: { attack: 1 },
    sellPrice: 25,
  },
  wateringcan_rare: {
    id: "wateringcan_rare",
    name: "Copper Watering Can",
    type: "tool",
    rarity: "rare",
    stats: { attack: 2 },
    sellPrice: 70,
  },
  wateringcan_epic: {
    id: "wateringcan_epic",
    name: "Mithril Watering Can",
    type: "tool",
    rarity: "epic",
    stats: { attack: 4 },
    sellPrice: 180,
  },
  wateringcan_legendary: {
    id: "wateringcan_legendary",
    name: "Royal Watering Can",
    type: "tool",
    rarity: "legendary",
    stats: { attack: 7 },
    sellPrice: 360,
  },
  wateringcan_unique: {
    id: "wateringcan_unique",
    name: "Verdant Watering Can",
    type: "tool",
    rarity: "unique",
    setId: "verdant",
    stats: { attack: 10 },
    sellPrice: 700,
  },

  // Scythes
  scythe_common: {
    id: "scythe_common",
    name: "Rusty Scythe",
    type: "tool",
    rarity: "common",
    stats: { attack: 2 },
    sellPrice: 35,
  },
  scythe_rare: {
    id: "scythe_rare",
    name: "Curved Scythe",
    type: "tool",
    rarity: "rare",
    stats: { attack: 5 },
    sellPrice: 85,
  },
  scythe_epic: {
    id: "scythe_epic",
    name: "Harvest Scythe",
    type: "tool",
    rarity: "epic",
    stats: { attack: 9 },
    sellPrice: 200,
  },
  scythe_legendary: {
    id: "scythe_legendary",
    name: "Reaper's Scythe",
    type: "tool",
    rarity: "legendary",
    stats: { attack: 14 },
    sellPrice: 420,
  },
  scythe_unique: {
    id: "scythe_unique",
    name: "Verdant Reaper",
    type: "tool",
    rarity: "unique",
    setId: "verdant",
    stats: { attack: 20 },
    sellPrice: 900,
  },

  // Seed Bags
  seedbag_common: {
    id: "seedbag_common",
    name: "Seed Bag",
    type: "tool",
    rarity: "common",
    sellPrice: 30,
  },
  seedbag_rare: {
    id: "seedbag_rare",
    name: "Seed Satchel",
    type: "tool",
    rarity: "rare",
    sellPrice: 90,
  },
  seedbag_epic: {
    id: "seedbag_epic",
    name: "Planter Pack",
    type: "tool",
    rarity: "epic",
    sellPrice: 220,
  },
  seedbag_legendary: {
    id: "seedbag_legendary",
    name: "Verdant Vault",
    type: "tool",
    rarity: "legendary",
    sellPrice: 420,
  },
  seedbag_unique: {
    id: "seedbag_unique",
    name: "Verdant Seed Cache",
    type: "tool",
    rarity: "unique",
    setId: "verdant",
    sellPrice: 800,
  },

  // Sprinklers
  sprinkler_common: {
    id: "sprinkler_common",
    name: "Basic Sprinkler",
    type: "tool",
    rarity: "common",
    sellPrice: 20,
  },
  sprinkler_rare: {
    id: "sprinkler_rare",
    name: "Standard Sprinkler",
    type: "tool",
    rarity: "rare",
    sellPrice: 60,
  },
  sprinkler_epic: {
    id: "sprinkler_epic",
    name: "Advanced Sprinkler",
    type: "tool",
    rarity: "epic",
    sellPrice: 150,
  },
  sprinkler_legendary: {
    id: "sprinkler_legendary",
    name: "Master Sprinkler",
    type: "tool",
    rarity: "legendary",
    sellPrice: 320,
  },
  sprinkler_unique: {
    id: "sprinkler_unique",
    name: "Verdant Sprinkler",
    type: "tool",
    rarity: "unique",
    setId: "verdant",
    sellPrice: 600,
  },

  // Harvesters
  harvester_common: {
    id: "harvester_common",
    name: "Basic Harvester",
    type: "tool",
    rarity: "common",
    sellPrice: 30,
  },
  harvester_rare: {
    id: "harvester_rare",
    name: "Field Harvester",
    type: "tool",
    rarity: "rare",
    sellPrice: 85,
  },
  harvester_epic: {
    id: "harvester_epic",
    name: "Pulse Harvester",
    type: "tool",
    rarity: "epic",
    sellPrice: 220,
  },
  harvester_legendary: {
    id: "harvester_legendary",
    name: "Royal Harvester",
    type: "tool",
    rarity: "legendary",
    sellPrice: 430,
  },
  harvester_unique: {
    id: "harvester_unique",
    name: "Verdant Harvester",
    type: "tool",
    rarity: "unique",
    setId: "verdant",
    sellPrice: 900,
  },

  // Planters
  planter_common: {
    id: "planter_common",
    name: "Basic Planter",
    type: "tool",
    rarity: "common",
    sellPrice: 30,
  },
  planter_rare: {
    id: "planter_rare",
    name: "Field Planter",
    type: "tool",
    rarity: "rare",
    sellPrice: 85,
  },
  planter_epic: {
    id: "planter_epic",
    name: "Pulse Planter",
    type: "tool",
    rarity: "epic",
    sellPrice: 220,
  },
  planter_legendary: {
    id: "planter_legendary",
    name: "Royal Planter",
    type: "tool",
    rarity: "legendary",
    sellPrice: 430,
  },
  planter_unique: {
    id: "planter_unique",
    name: "Verdant Planter",
    type: "tool",
    rarity: "unique",
    setId: "verdant",
    sellPrice: 900,
  },

  // Potions - Common
  health_potion: {
    id: "health_potion",
    name: "Health Potion",
    type: "potion",
    rarity: "common",
    sellPrice: 20,
  },
  // Potions - Rare
  mana_potion: {
    id: "mana_potion",
    name: "Mana Potion",
    type: "potion",
    rarity: "rare",
    stats: { intelligence: 2 },
    sellPrice: 50,
  },
  // Potions - Epic
  elixir: {
    id: "elixir",
    name: "Elixir of Power",
    type: "potion",
    rarity: "epic",
    stats: { attack: 3, intelligence: 3 },
    sellPrice: 150,
  },
  // Potions - Legendary
  immortal_brew: {
    id: "immortal_brew",
    name: "Immortal Brew",
    type: "potion",
    rarity: "legendary",
    stats: { attack: 8, defense: 8, intelligence: 8 },
    sellPrice: 300,
  },
  // Potions - Rare (new)
  swift_tonic: {
    id: "swift_tonic",
    name: "Swift Tonic",
    type: "potion",
    rarity: "rare",
    sellPrice: 45,
  },
  fortitude_brew: {
    id: "fortitude_brew",
    name: "Brew of Fortitude",
    type: "potion",
    rarity: "rare",
    stats: { defense: 3 },
    sellPrice: 55,
  },
  // Potions - Epic (new)
  scholars_draught: {
    id: "scholars_draught",
    name: "Scholar's Draught",
    type: "potion",
    rarity: "epic",
    stats: { intelligence: 5 },
    sellPrice: 180,
  },
  berserkers_tonic: {
    id: "berserkers_tonic",
    name: "Berserker's Tonic",
    type: "potion",
    rarity: "epic",
    stats: { attack: 10, defense: -3 },
    sellPrice: 160,
  },
  // Potions - Unique (new)
  chaos_potion: {
    id: "chaos_potion",
    name: "Voidborn Elixir",
    type: "potion",
    rarity: "unique",
    setId: "voidborn",
    sellPrice: 500,
  },

  // Seeds aligned with garden crop configuration
  sunflower_seed_common: {
    id: "sunflower_seed_common",
    name: "Sunflower Seed",
    type: "seed",
    rarity: "common",
    sellPrice: 5,
  },
  carrot_seed_common: {
    id: "carrot_seed_common",
    name: "Carrot Seed",
    type: "seed",
    rarity: "common",
    sellPrice: 5,
  },
  apple_seed_common: {
    id: "apple_seed_common",
    name: "Apple Seed",
    type: "seed",
    rarity: "common",
    sellPrice: 5,
  },
  mint_seed_common: {
    id: "mint_seed_common",
    name: "Mint Seed",
    type: "seed",
    rarity: "common",
    sellPrice: 5,
  },
  wheat_seed_common: {
    id: "wheat_seed_common",
    name: "Wheat Seed",
    type: "seed",
    rarity: "common",
    sellPrice: 5,
  },
  grape_seed_common: {
    id: "grape_seed_common",
    name: "Grape Seed",
    type: "seed",
    rarity: "common",
    sellPrice: 5,
  },
  rose_seed_rare: {
    id: "rose_seed_rare",
    name: "Rose Seed",
    type: "seed",
    rarity: "rare",
    sellPrice: 15,
  },
  starlime_seed_rare: {
    id: "starlime_seed_rare",
    name: "Starlime Seed",
    type: "seed",
    rarity: "rare",
    sellPrice: 24,
  },
  coralfern_seed_rare: {
    id: "coralfern_seed_rare",
    name: "Coralfern Seed",
    type: "seed",
    rarity: "rare",
    sellPrice: 24,
  },
  cabbage_seed_rare: {
    id: "cabbage_seed_rare",
    name: "Cabbage Seed",
    type: "seed",
    rarity: "rare",
    sellPrice: 15,
  },
  berry_seed_rare: {
    id: "berry_seed_rare",
    name: "Berry Seed",
    type: "seed",
    rarity: "rare",
    sellPrice: 15,
  },
  corn_seed_rare: {
    id: "corn_seed_rare",
    name: "Corn Seed",
    type: "seed",
    rarity: "rare",
    sellPrice: 15,
  },
  astral_lotus_seed_epic: {
    id: "astral_lotus_seed_epic",
    name: "Astral Lotus Seed",
    type: "seed",
    rarity: "epic",
    sellPrice: 80,
  },
  void_truffle_seed_legendary: {
    id: "void_truffle_seed_legendary",
    name: "Void Truffle Seed",
    type: "seed",
    rarity: "legendary",
    sellPrice: 180,
  },
  phoenix_bloom_seed_unique: {
    id: "phoenix_bloom_seed_unique",
    name: "Phoenix Bloom Seed",
    type: "seed",
    rarity: "unique",
    sellPrice: 420,
  },
  // Seeds - Epic
  moonflower_seed: {
    id: "moonflower_seed",
    name: "Moonflower Seed",
    type: "seed",
    rarity: "epic",
    stats: { intelligence: 1 },
    sellPrice: 40,
  },
  moonpalm_seed_epic: {
    id: "moonpalm_seed_epic",
    name: "Moonpalm Seed",
    type: "seed",
    rarity: "epic",
    sellPrice: 95,
  },
  dragonfruit_seed_epic: {
    id: "dragonfruit_seed_epic",
    name: "Dragonfruit Seed",
    type: "seed",
    rarity: "epic",
    sellPrice: 95,
  },
  // Seeds - Legendary
  yggdrasil_seed: {
    id: "yggdrasil_seed",
    name: "Yggdrasil Seed",
    type: "seed",
    rarity: "legendary",
    stats: { attack: 5, defense: 5 },
    sellPrice: 200,
  },
  aurora_orchid_seed_legendary: {
    id: "aurora_orchid_seed_legendary",
    name: "Aurora Orchid Seed",
    type: "seed",
    rarity: "legendary",
    sellPrice: 240,
  },
  lava_blossom_seed_legendary: {
    id: "lava_blossom_seed_legendary",
    name: "Lava Blossom Seed",
    type: "seed",
    rarity: "legendary",
    sellPrice: 240,
  },

  // Pets - Common
  wolf_pup: {
    id: "wolf_pup",
    name: "Wolf Pup",
    type: "pet",
    rarity: "common",
    stats: { attack: 2 },
    sellPrice: 60,
    petBonus: { bonusType: "attack", bonusAmount: 0.05 }, // 5% attack bonus per level
  },
  // Pets - Rare
  fire_fox: {
    id: "fire_fox",
    name: "Fire Fox",
    type: "pet",
    rarity: "rare",
    stats: { attack: 16, intelligence: 12 },
    sellPrice: 120,
    petBonus: { bonusType: "goldIncome", bonusAmount: 0.1 }, // 10% gold income bonus per level
  },
  thunder_lynx: {
    id: "thunder_lynx",
    name: "Thunder Lynx",
    type: "pet",
    rarity: "rare",
    stats: { attack: 24, agility: 14, critChance: 6 },
    sellPrice: 170,
    petBonus: { bonusType: "attack", bonusAmount: 0.14 },
  },
  // Pets - Epic
  ice_dragon: {
    id: "ice_dragon",
    name: "Ice Dragon",
    type: "pet",
    rarity: "epic",
    stats: { attack: 120, defense: 90, intelligence: 90 },
    sellPrice: 400,
    petBonus: { bonusType: "defense", bonusAmount: 0.12 }, // 12% defense bonus per level
  },
  storm_griffin: {
    id: "storm_griffin",
    name: "Storm Griffin",
    type: "pet",
    rarity: "epic",
    stats: { attack: 150, agility: 80, critChance: 24 },
    sellPrice: 520,
    petBonus: { bonusType: "agility", bonusAmount: 0.2 },
  },
  // Pets - Legendary
  phoenix: {
    id: "phoenix",
    name: "Phoenix",
    type: "pet",
    rarity: "legendary",
    stats: { attack: 2600, intelligence: 2100, energyRegeneration: 180 },
    sellPrice: 600,
    petBonus: { bonusType: "intelligence", bonusAmount: 0.15 }, // 15% intelligence bonus per level
  },
  astral_phoenix: {
    id: "astral_phoenix",
    name: "Astral Phoenix",
    type: "pet",
    rarity: "legendary",
    stats: { attack: 3200, intelligence: 2600, critChance: 60 },
    sellPrice: 1200,
    petBonus: { bonusType: "energyRegeneration", bonusAmount: 0.32 },
  },
  // Pets - Unique
  void_beast: {
    id: "void_beast",
    name: "Voidborn Beast",
    type: "pet",
    rarity: "unique",
    setId: "voidborn",
    stats: { attack: 110000, defense: 52000, intelligence: 56000 },
    sellPrice: 1000,
    petBonus: { bonusType: "attack", bonusAmount: 0.95 },
  },
  astral_wolf: {
    id: "astral_wolf",
    name: "Arcaneforge Wolf",
    type: "pet",
    rarity: "unique",
    setId: "arcaneforge",
    stats: { attack: 98000, intelligence: 84000, energyRegeneration: 480 },
    sellPrice: 2000,
    petBonus: { bonusType: "intelligence", bonusAmount: 1.05 },
  },
  grove_colossus: {
    id: "grove_colossus",
    name: "Verdant Colossus",
    type: "pet",
    rarity: "unique",
    setId: "verdant",
    stats: { attack: 86000, hp: 320000, plantGrowth: 480 },
    sellPrice: 1980,
    petBonus: { bonusType: "plantGrowth", bonusAmount: 1.2 },
  },
  storm_hydra: {
    id: "storm_hydra",
    name: "Beastlord Hydra",
    type: "pet",
    rarity: "unique",
    setId: "beastlord",
    stats: { attack: 126000, defense: 68000, agility: 520 },
    sellPrice: 2100,
    petBonus: { bonusType: "attack", bonusAmount: 1.3 },
  },
  blood_raptor: {
    id: "blood_raptor",
    name: "Blood Raptor",
    type: "pet",
    rarity: "unique",
    setId: "bloodletter",
    stats: { attack: 122000, agility: 640, intelligence: 28000 },
    sellPrice: 2120,
    petBonus: { bonusType: "agility", bonusAmount: 1.35 },
  },
  windrazor_raptor: {
    id: "windrazor_raptor",
    name: "Windrazor Raptor",
    type: "pet",
    rarity: "unique",
    setId: "windrazor",
    stats: { attack: 118000, agility: 820, critChance: 140 },
    sellPrice: 2140,
    petBonus: { bonusType: "agility", bonusAmount: 1.6 },
  },
  gorelord_warg: {
    id: "gorelord_warg",
    name: "Gorelord Warg",
    type: "pet",
    rarity: "unique",
    setId: "gorelord",
    stats: { attack: 182000, hp: 460000, critChance: 320 },
    sellPrice: 2620,
    petBonus: { bonusType: "attack", bonusAmount: 2 },
  },
  nightstar_drake: {
    id: "nightstar_drake",
    name: "Nightstar Drake",
    type: "pet",
    rarity: "unique",
    setId: "nightstar",
    stats: { attack: 170000, intelligence: 210000, energyRegeneration: 1200 },
    sellPrice: 2640,
    petBonus: { bonusType: "intelligence", bonusAmount: 2.1 },
  },
  rootcrown_colossus: {
    id: "rootcrown_colossus",
    name: "Rootcrown Colossus",
    type: "pet",
    rarity: "unique",
    setId: "rootcrown",
    stats: { attack: 162000, hp: 620000, plantGrowth: 2000 },
    sellPrice: 2660,
    petBonus: { bonusType: "plantGrowth", bonusAmount: 2.3 },
  },
  skyhunter_gryphon: {
    id: "skyhunter_gryphon",
    name: "Skyhunter Gryphon",
    type: "pet",
    rarity: "unique",
    setId: "skyhunter",
    stats: { attack: 180000, agility: 2100, critChance: 340 },
    sellPrice: 2680,
    petBonus: { bonusType: "agility", bonusAmount: 2.2 },
  },
  epochveil_wyrm: {
    id: "epochveil_wyrm",
    name: "Epochveil Wyrm",
    type: "pet",
    rarity: "unique",
    setId: "epochveil",
    stats: { attack: 174000, goldIncome: 3200, energyRegeneration: 1280 },
    sellPrice: 2700,
    petBonus: { bonusType: "goldIncome", bonusAmount: 2.4 },
  },
  moonpack_alpha: {
    id: "moonpack_alpha",
    name: "Moonpack Alpha",
    type: "pet",
    rarity: "unique",
    setId: "moonpack",
    stats: { attack: 186000, petStrength: 2400, hp: 520000 },
    sellPrice: 2720,
    petBonus: { bonusType: "attack", bonusAmount: 2.25 },
  },
};
