import type { CharacterClassDefinition } from "../types";

export const archerClass: CharacterClassDefinition = {
  id: "archer",
  name: "Archer",
  summary: "Hyper-fast attacks, on-hit synergies, and cap-breaking tempo.",
  fantasy: "A relentless volley specialist that drowns enemies in strikes.",
  portraitAsset: "archer",
  nodes: [
    {
      id: "archer_1",
      name: "Rapid Draw",
      description: "APS +0.22 per rank, Agility +3 per rank.",
      maxRank: 5,
    },
    {
      id: "archer_2",
      name: "Needle Rain",
      description: "All Damage +2% per rank, Attack +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["archer_1"],
    },
    {
      id: "archer_3",
      name: "Click Reflex",
      description: "Click Damage +3.5% per rank, Attack +2.2 per rank.",
      maxRank: 5,
      prerequisites: ["archer_1"],
    },
    {
      id: "archer_synergy",
      name: "Marks Focus",
      description:
        "Unlock Active Skill Marks Focus: your next Archer spell deals 5x damage.",
      maxRank: 1,
      prerequisites: ["archer_2"],
    },
    {
      id: "archer_4",
      name: "Windstep",
      description: "APS +0.34 per rank, Agility +3 per rank.",
      maxRank: 5,
      prerequisites: ["archer_2"],
    },
    {
      id: "archer_5",
      name: "Piercing Thread",
      description: "Crit Chance +1.6% per rank.",
      maxRank: 3,
      prerequisites: ["archer_2"],
    },
    {
      id: "archer_6",
      name: "Elastic String",
      description:
        "APS Multiplier +8% per rank, Agility +2.4 per rank, APS Cap +2 per rank.",
      maxRank: 5,
      prerequisites: ["archer_3"],
    },
    {
      id: "archer_7",
      name: "Volley Rhythm",
      description: "APS Multiplier +3% per rank, Agility +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["archer_4"],
    },
    {
      id: "archer_8",
      name: "Shatter Nocks",
      description: "Crit Chance +1% per rank, Reduce enemy defense.",
      maxRank: 3,
      prerequisites: ["archer_5"],
    },
    {
      id: "archer_9",
      name: "Hunter Focus",
      description: "All Damage +1.5% per rank, Attack +2.8 per rank.",
      maxRank: 5,
      prerequisites: ["archer_6"],
    },
    {
      id: "archer_10",
      name: "Storm Quiver",
      description: "Pet Proc Chance +2% per rank, additional hit procs.",
      maxRank: 3,
      prerequisites: ["archer_7", "archer_8"],
    },
    {
      id: "archer_11",
      name: "Skyline Step",
      description:
        "APS Multiplier +6%, Agility +4.2, sustain at high attack speed.",
      maxRank: 1,
      prerequisites: ["archer_9"],
    },
    {
      id: "archer_12",
      name: "Arrow Tempest",
      description:
        "All Damage +16%, APS Cap +20, Attack +12, Crit Chance +4%. Capstone.",
      maxRank: 1,
      prerequisites: ["archer_10", "archer_11"],
    },
    {
      id: "archer_13",
      name: "Falcon Fingers",
      description: "APS +0.28 per rank, Agility +2.6 per rank.",
      maxRank: 5,
      prerequisites: ["archer_12"],
    },
    {
      id: "archer_14",
      name: "Deadeye Knots",
      description: "Crit Chance +1.2% per rank, Attack +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["archer_12"],
    },
    {
      id: "archer_15",
      name: "Ricochet Wrist",
      description: "Click Damage +4% per rank, Attack +2.8 per rank.",
      maxRank: 5,
      prerequisites: ["archer_13"],
    },
    {
      id: "archer_16",
      name: "Barbed Flights",
      description: "All Damage +2.5% per rank, Crit Chance +0.5% per rank.",
      maxRank: 5,
      prerequisites: ["archer_14"],
    },
    {
      id: "archer_17",
      name: "Slipstream Stance",
      description: "APS Multiplier +4% per rank, Agility +2.6 per rank.",
      maxRank: 5,
      prerequisites: ["archer_15"],
    },
    {
      id: "archer_18",
      name: "Raptor Signal",
      description: "Pet Proc Chance +1.5% per rank, All Damage +2% per rank.",
      maxRank: 3,
      prerequisites: ["archer_16"],
    },
    {
      id: "archer_19",
      name: "Horizon Measure",
      description: "Crit Chance +1.5% per rank, APS Cap +2 per rank.",
      maxRank: 5,
      prerequisites: ["archer_17"],
    },
    {
      id: "archer_20",
      name: "Quiver Cyclone",
      description: "APS Multiplier +5% per rank, All Damage +2% per rank.",
      maxRank: 3,
      prerequisites: ["archer_18", "archer_19"],
    },
    {
      id: "archer_21",
      name: "Skyhook Line",
      description: "APS Cap +12, All Damage +8%, Crit Chance +2%.",
      maxRank: 1,
      prerequisites: ["archer_19"],
    },
    {
      id: "archer_22",
      name: "Heavenfall Volley",
      description:
        "All Damage +16%, Crit Chance +4%, APS Multiplier +8%. Final capstone.",
      maxRank: 1,
      prerequisites: ["archer_20", "archer_21"],
    },
  ],
  classSpells: [
    {
      id: "archer_marks_focus",
      name: "Marks Focus",
      description:
        "Steady your aim so your next Archer spell lands with overwhelming precision.",
      manaCost: 22,
      cooldownMs: 30000,
      requiredLevel: 12,
    },
    {
      id: "archer_hailfire",
      name: "Hailfire",
      description: "Unload a compressed hail of brutal high-speed arrows.",
      manaCost: 28,
      cooldownMs: 18000,
      requiredLevel: 10,
    },
    {
      id: "archer_pinpoint",
      name: "Pinpoint Volley",
      description:
        "Thread a lethal multi-volley straight through the weak point.",
      manaCost: 38,
      cooldownMs: 23000,
      requiredLevel: 20,
    },
    {
      id: "archer_ricochet_gale",
      name: "Ricochet Gale",
      description:
        "A cutting spray of arrows that rebounds through the target.",
      manaCost: 40,
      cooldownMs: 25000,
      requiredLevel: 24,
    },
    {
      id: "archer_deadeye_brand",
      name: "Deadeye Brand",
      description: "Brand the foe with a single catastrophic marksman shot.",
      manaCost: 46,
      cooldownMs: 29000,
      requiredLevel: 28,
    },
    {
      id: "archer_featherstorm",
      name: "Featherstorm",
      description:
        "A dense storm of sharp shots with punishing follow-through.",
      manaCost: 52,
      cooldownMs: 33000,
      requiredLevel: 32,
    },
    {
      id: "archer_splitshot_drive",
      name: "Splitshot Drive",
      description: "Burst into a rapid chain of heavy split arrows.",
      manaCost: 58,
      cooldownMs: 37000,
      requiredLevel: 36,
    },
    {
      id: "archer_horizon_break",
      name: "Horizon Break",
      description: "Break the skyline with a long-range armor-breaking cast.",
      manaCost: 64,
      cooldownMs: 43000,
      requiredLevel: 40,
    },
    {
      id: "archer_siege_volley",
      name: "Siege Volley",
      description: "Fire a siege-grade barrage meant to end the exchange.",
      manaCost: 70,
      cooldownMs: 49000,
      requiredLevel: 44,
    },
    {
      id: "archer_falconfall",
      name: "Falconfall",
      description: "Dive the target with a pinpoint rain of killing shots.",
      manaCost: 76,
      cooldownMs: 56000,
      requiredLevel: 48,
    },
    {
      id: "archer_zenith_barrage",
      name: "Zenith Barrage",
      description:
        "Rain a final impossible barrage from the very top of range.",
      manaCost: 84,
      cooldownMs: 64000,
      requiredLevel: 52,
    },
  ],
};
