import type { CharacterClassDefinition } from "../types";

export const archerClass: CharacterClassDefinition = {
  id: "archer",
  name: "Archer",
  summary: "Hyper-fast attacks, on-hit synergies, and cap-breaking tempo.",
  fantasy: "A relentless volley specialist that drowns enemies in strikes.",
  portraitAsset: "archer",
  nodes: [
    {
      id: "archer_1",
      name: "Rapid Draw",
      description: "Increase attack speed scaling.",
      maxRank: 5,
    },
    {
      id: "archer_2",
      name: "Needle Rain",
      description: "Boost on-hit bonus damage.",
      maxRank: 5,
      prerequisites: ["archer_1"],
    },
    {
      id: "archer_3",
      name: "Click Reflex",
      description: "Improve click/on-click burst.",
      maxRank: 5,
      prerequisites: ["archer_1"],
    },
    {
      id: "archer_4",
      name: "Windstep",
      description: "Convert agility into extra APS.",
      maxRank: 5,
      prerequisites: ["archer_2"],
    },
    {
      id: "archer_5",
      name: "Piercing Thread",
      description: "Raise crit consistency at high APS.",
      maxRank: 3,
      prerequisites: ["archer_2"],
    },
    {
      id: "archer_6",
      name: "Elastic String",
      description: "Increase APS cap contribution.",
      maxRank: 5,
      prerequisites: ["archer_3"],
    },
    {
      id: "archer_7",
      name: "Volley Rhythm",
      description: "Every burst cycle accelerates further.",
      maxRank: 5,
      prerequisites: ["archer_4"],
    },
    {
      id: "archer_8",
      name: "Shatter Nocks",
      description: "On-hit reduces enemy durability.",
      maxRank: 3,
      prerequisites: ["archer_5"],
    },
    {
      id: "archer_9",
      name: "Hunter Focus",
      description: "Scale damage with current APS.",
      maxRank: 5,
      prerequisites: ["archer_6"],
    },
    {
      id: "archer_10",
      name: "Storm Quiver",
      description: "Duplicate a share of hits.",
      maxRank: 3,
      prerequisites: ["archer_7", "archer_8"],
    },
    {
      id: "archer_11",
      name: "Skyline Step",
      description: "Sustain speed through combat pressure.",
      maxRank: 1,
      prerequisites: ["archer_9"],
    },
    {
      id: "archer_12",
      name: "Arrow Tempest",
      description: "Capstone that melts HP bars with extreme rate.",
      maxRank: 1,
      prerequisites: ["archer_10", "archer_11"],
    },
  ],
  classSpells: [
    {
      id: "archer_hailfire",
      name: "Hailfire",
      description: "Massively increase attacks per second for a short burst.",
      manaCost: 28,
      cooldownMs: 14000,
      requiredLevel: 10,
    },
    {
      id: "archer_pinpoint",
      name: "Pinpoint Volley",
      description: "High-frequency multishot with on-hit scaling.",
      manaCost: 38,
      cooldownMs: 17000,
      requiredLevel: 20,
    },
  ],
};
