import type { CharacterClassDefinition } from "../types";

export const berserkerClass: CharacterClassDefinition = {
  id: "berserker",
  name: "Berserker",
  summary: "Slow, crushing hits with explosive burst windows.",
  fantasy: "A relentless executioner who wins by overwhelming impact.",
  portraitAsset: "berserker",
  nodes: [
    {
      id: "berserker_1",
      name: "Heavy Momentum",
      description: "Heavy Hit Damage +3.5% per rank.",
      maxRank: 5,
    },
    {
      id: "berserker_2",
      name: "Blood Tempo",
      description: "Click Damage +3% per rank, Agility +2.5 per rank.",
      maxRank: 3,
      prerequisites: ["berserker_1"],
    },
    {
      id: "berserker_3",
      name: "Skullsplit",
      description:
        "Reduce Incoming Damage by 2% per rank, Defense +2.2 per rank.",
      maxRank: 5,
      prerequisites: ["berserker_1"],
    },
    {
      id: "berserker_4",
      name: "Execution Rhythm",
      description: "Crit Chance +1.25% per rank.",
      maxRank: 3,
      prerequisites: ["berserker_2"],
    },
    {
      id: "berserker_5",
      name: "Carnage Fuel",
      description:
        "Mana gain on Hit +0.9 per rank, Energy Regen +3.8 per rank.",
      maxRank: 3,
      prerequisites: ["berserker_2"],
    },
    {
      id: "berserker_6",
      name: "Iron Appetite",
      description: "Lifesteal +0.9% per rank, HP +7.5 per rank.",
      maxRank: 5,
      prerequisites: ["berserker_3"],
    },
    {
      id: "berserker_7",
      name: "War Roar",
      description: "Spell Damage +6% per rank, Attack +3.2 per rank.",
      maxRank: 3,
      prerequisites: ["berserker_4"],
    },
    {
      id: "berserker_8",
      name: "Crimson Trail",
      description: "All Damage +2% per rank, Crit Chance +1.2% per rank.",
      maxRank: 5,
      prerequisites: ["berserker_5"],
    },
    {
      id: "berserker_9",
      name: "Titan Grip",
      description: "All Damage +4% per rank (stacking), Attack +5.8 per rank.",
      maxRank: 3,
      prerequisites: ["berserker_6"],
    },
    {
      id: "berserker_10",
      name: "Ruin Pulse",
      description: "All Damage +3% per rank, Attack +3.6 per rank.",
      maxRank: 5,
      prerequisites: ["berserker_7", "berserker_8"],
    },
    {
      id: "berserker_11",
      name: "Unbroken",
      description:
        "Survive lethal hit with 35% chance and heal to 18% HP. Defense +8.5, HP +12.",
      maxRank: 1,
      prerequisites: ["berserker_9"],
    },
    {
      id: "berserker_12",
      name: "Apex Butcher",
      description: "All Damage +20%, Attack +14, HP +20. Capstone.",
      maxRank: 1,
      prerequisites: ["berserker_10", "berserker_11"],
    },
    {
      id: "berserker_13",
      name: "Butcher's Reach",
      description: "All Damage +2.5% per rank, Crit Chance +0.7% per rank.",
      maxRank: 5,
      prerequisites: ["berserker_12"],
    },
    {
      id: "berserker_14",
      name: "Battle Trance",
      description: "Spell Damage +7% per rank, Mana gain on Hit +0.6 per rank.",
      maxRank: 5,
      prerequisites: ["berserker_12"],
    },
    {
      id: "berserker_15",
      name: "Bone Furnace",
      description: "Lifesteal +1.1% per rank, HP +6 per rank.",
      maxRank: 5,
      prerequisites: ["berserker_13"],
    },
    {
      id: "berserker_16",
      name: "Sunder Pulse",
      description: "Click Damage +4% per rank, Attack +3.5 per rank.",
      maxRank: 5,
      prerequisites: ["berserker_13"],
    },
    {
      id: "berserker_17",
      name: "Rage Vortex",
      description: "Crit Chance +1.5% per rank, Spell Damage +3% per rank.",
      maxRank: 3,
      prerequisites: ["berserker_14"],
    },
    {
      id: "berserker_18",
      name: "Gore Engine",
      description: "Mana gain on Hit +1.2 per rank, Spell Damage +4% per rank.",
      maxRank: 3,
      prerequisites: ["berserker_15"],
    },
    {
      id: "berserker_19",
      name: "Maw of Iron",
      description:
        "Reduce Incoming Damage by 1.5% per rank, All Damage +2% per rank.",
      maxRank: 5,
      prerequisites: ["berserker_16"],
    },
    {
      id: "berserker_20",
      name: "Killing Horizon",
      description: "All Damage +5% per rank, Crit Chance +1% per rank.",
      maxRank: 3,
      prerequisites: ["berserker_17", "berserker_18"],
    },
    {
      id: "berserker_21",
      name: "Red Dominion",
      description: "Lifesteal +3%, All Damage +8%, HP +18.",
      maxRank: 1,
      prerequisites: ["berserker_19"],
    },
    {
      id: "berserker_22",
      name: "Worldsplitter",
      description:
        "All Damage +18%, Spell Damage +12%, Crit Chance +3%. Final capstone.",
      maxRank: 1,
      prerequisites: ["berserker_20", "berserker_21"],
    },
  ],
  classSpells: [
    {
      id: "berserker_warcry",
      name: "Warcry",
      description: "Detonate a brutal shock roar that caves in the target.",
      manaCost: 35,
      cooldownMs: 22000,
      requiredLevel: 10,
    },
    {
      id: "berserker_execution",
      name: "Executioner Stance",
      description:
        "Commit to a devastating finisher that scales with missing HP.",
      manaCost: 50,
      cooldownMs: 32000,
      requiredLevel: 20,
    },
    {
      id: "berserker_ruin_crash",
      name: "Ruin Crash",
      description: "Bring down a two-handed slam that cracks armor and bone.",
      manaCost: 42,
      cooldownMs: 24000,
      requiredLevel: 24,
    },
    {
      id: "berserker_blood_comet",
      name: "Blood Comet",
      description: "A red-hot impact strike that scales hard with Attack.",
      manaCost: 48,
      cooldownMs: 28000,
      requiredLevel: 28,
    },
    {
      id: "berserker_chain_rend",
      name: "Chain Rend",
      description: "Tear through the enemy with repeated execution arcs.",
      manaCost: 55,
      cooldownMs: 33000,
      requiredLevel: 32,
    },
    {
      id: "berserker_slaughter_drive",
      name: "Slaughter Drive",
      description: "Unleash a surge of killing intent in one crushing blow.",
      manaCost: 58,
      cooldownMs: 36000,
      requiredLevel: 36,
    },
    {
      id: "berserker_iron_meteor",
      name: "Iron Meteor",
      description: "Call down a falling strike with catastrophic force.",
      manaCost: 64,
      cooldownMs: 41000,
      requiredLevel: 40,
    },
    {
      id: "berserker_skull_banner",
      name: "Skull Banner",
      description: "Mark the foe for annihilation with a brutal war standard.",
      manaCost: 68,
      cooldownMs: 46000,
      requiredLevel: 44,
    },
    {
      id: "berserker_cataclysm_chop",
      name: "Cataclysm Chop",
      description: "Deliver a battlefield-ending cleave through the target.",
      manaCost: 74,
      cooldownMs: 52000,
      requiredLevel: 48,
    },
    {
      id: "berserker_doom_feast",
      name: "Doom Feast",
      description: "Consume the fight in one final, ravenous execution blow.",
      manaCost: 82,
      cooldownMs: 60000,
      requiredLevel: 52,
    },
  ],
};
