import type { CharacterClassDefinition } from "../types";

export const berserkerClass: CharacterClassDefinition = {
  id: "berserker",
  name: "Berserker",
  summary: "Slow, crushing hits with explosive burst windows.",
  fantasy: "A relentless executioner who wins by overwhelming impact.",
  portraitAsset: "berserker",
  nodes: [
    {
      id: "berserker_1",
      name: "Heavy Momentum",
      description: "Increase heavy hit damage.",
      maxRank: 5,
    },
    {
      id: "berserker_2",
      name: "Blood Tempo",
      description: "Gain burst windows after crits.",
      maxRank: 3,
      prerequisites: ["berserker_1"],
    },
    {
      id: "berserker_3",
      name: "Skullsplit",
      description: "Chance to shatter defense.",
      maxRank: 5,
      prerequisites: ["berserker_1"],
    },
    {
      id: "berserker_4",
      name: "Execution Rhythm",
      description: "Boost damage against high-HP enemies.",
      maxRank: 3,
      prerequisites: ["berserker_2"],
    },
    {
      id: "berserker_5",
      name: "Carnage Fuel",
      description: "Recover mana from heavy hits.",
      maxRank: 3,
      prerequisites: ["berserker_2"],
    },
    {
      id: "berserker_6",
      name: "Iron Appetite",
      description: "Leech small HP on hit.",
      maxRank: 5,
      prerequisites: ["berserker_3"],
    },
    {
      id: "berserker_7",
      name: "War Roar",
      description: "Amplify burst spell uptime.",
      maxRank: 3,
      prerequisites: ["berserker_4"],
    },
    {
      id: "berserker_8",
      name: "Crimson Trail",
      description: "Apply stacking bleed.",
      maxRank: 5,
      prerequisites: ["berserker_5"],
    },
    {
      id: "berserker_9",
      name: "Titan Grip",
      description: "Massively increase weapon scaling.",
      maxRank: 3,
      prerequisites: ["berserker_6"],
    },
    {
      id: "berserker_10",
      name: "Ruin Pulse",
      description: "Every nth hit deals huge bonus damage.",
      maxRank: 5,
      prerequisites: ["berserker_7", "berserker_8"],
    },
    {
      id: "berserker_11",
      name: "Unbroken",
      description: "Temporary damage immunity on lethal hit.",
      maxRank: 1,
      prerequisites: ["berserker_9"],
    },
    {
      id: "berserker_12",
      name: "Apex Butcher",
      description: "Capstone burst multiplier for heavy strikes.",
      maxRank: 1,
      prerequisites: ["berserker_10", "berserker_11"],
    },
  ],
  classSpells: [
    {
      id: "berserker_warcry",
      name: "Warcry",
      description: "Massively increase damage for a short window.",
      manaCost: 35,
      cooldownMs: 18000,
      requiredLevel: 10,
    },
    {
      id: "berserker_execution",
      name: "Executioner Stance",
      description: "Sacrifice speed for enormous hit damage.",
      manaCost: 50,
      cooldownMs: 26000,
      requiredLevel: 20,
    },
  ],
};
