import type { CharacterClassDefinition } from "../types";

export const farmerClass: CharacterClassDefinition = {
  id: "farmer",
  name: "Farmer",
  summary: "Sustain combatant with strong garden growth and harvest rewards.",
  fantasy: "A cultivator who turns resilience and harvest into power.",
  portraitAsset: "farmer",
  nodes: [
    {
      id: "farmer_1",
      name: "Field Medicine",
      description: "Increase self-healing.",
      maxRank: 5,
    },
    {
      id: "farmer_2",
      name: "Irrigation Instinct",
      description: "Boost watering and growth effects.",
      maxRank: 5,
      prerequisites: ["farmer_1"],
    },
    {
      id: "farmer_3",
      name: "Rooted Guard",
      description: "Gain defense while healthy.",
      maxRank: 5,
      prerequisites: ["farmer_1"],
    },
    {
      id: "farmer_4",
      name: "Bountiful Hands",
      description: "Increase base harvest yield.",
      maxRank: 5,
      prerequisites: ["farmer_2"],
    },
    {
      id: "farmer_5",
      name: "Dawn Tonic",
      description: "Regenerate HP over time in combat.",
      maxRank: 3,
      prerequisites: ["farmer_2"],
    },
    {
      id: "farmer_6",
      name: "Granary Mind",
      description: "Increase special crop conversion value.",
      maxRank: 5,
      prerequisites: ["farmer_3"],
    },
    {
      id: "farmer_7",
      name: "Hardy Stem",
      description: "Increase max HP scaling.",
      maxRank: 5,
      prerequisites: ["farmer_4"],
    },
    {
      id: "farmer_8",
      name: "Harvest Surge",
      description: "Gain temporary buffs after harvesting.",
      maxRank: 3,
      prerequisites: ["farmer_5"],
    },
    {
      id: "farmer_9",
      name: "Seed Fortune",
      description: "Increase special seed drop chance tiers.",
      maxRank: 5,
      prerequisites: ["farmer_6"],
    },
    {
      id: "farmer_10",
      name: "Sunrise Feast",
      description: "Large periodic heal in combat.",
      maxRank: 3,
      prerequisites: ["farmer_7", "farmer_8"],
    },
    {
      id: "farmer_11",
      name: "Vault of Seasons",
      description: "Boost all garden-relevant stats.",
      maxRank: 1,
      prerequisites: ["farmer_9"],
    },
    {
      id: "farmer_12",
      name: "Verdant Sovereign",
      description: "Capstone for sustain and harvest power.",
      maxRank: 1,
      prerequisites: ["farmer_10", "farmer_11"],
    },
  ],
  classSpells: [
    {
      id: "farmer_regrowth",
      name: "Regrowth",
      description: "Heal instantly and apply heal-over-time.",
      manaCost: 30,
      cooldownMs: 14000,
      requiredLevel: 10,
    },
    {
      id: "farmer_harvest_guard",
      name: "Harvest Guard",
      description: "Damage reduction and regen during combat.",
      manaCost: 40,
      cooldownMs: 22000,
      requiredLevel: 20,
    },
  ],
};
