import type { CharacterClassDefinition } from "../types";

export const idlerClass: CharacterClassDefinition = {
  id: "idler",
  name: "Idler",
  summary: "Offline scaling and escalating daily check-in streak rewards.",
  fantasy: "A strategist who profits most from patience and consistency.",
  portraitAsset: "idler",
  nodes: [
    {
      id: "idler_1",
      name: "Long Arc",
      description: "Offline Gold +4.5 per rank.",
      maxRank: 5,
    },
    {
      id: "idler_2",
      name: "Silent Ledger",
      description: "Offline Gold +4.8 per rank, Attack +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["idler_1"],
    },
    {
      id: "idler_3",
      name: "Resting Edge",
      description:
        "Damage +2% per rank after returning online, Attack +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["idler_1"],
    },
    {
      id: "idler_4",
      name: "Streak Keeper",
      description:
        "Daily Streak Rewards +1% per rank, Gold Income +3.2 per rank.",
      maxRank: 5,
      prerequisites: ["idler_2"],
    },
    {
      id: "idler_5",
      name: "Quiet Reserve",
      description:
        "Mana Restore Multiplier +6% per rank, Energy Regen +4.2 per rank.",
      maxRank: 3,
      prerequisites: ["idler_2"],
    },
    {
      id: "idler_6",
      name: "Delayed Impact",
      description: "Damage +2% per rank on return, Attack +2.6 per rank.",
      maxRank: 5,
      prerequisites: ["idler_3"],
    },
    {
      id: "idler_7",
      name: "Patience Dividend",
      description: "Offline Gold scales by absence duration +4.2 per rank.",
      maxRank: 5,
      prerequisites: ["idler_4"],
    },
    {
      id: "idler_8",
      name: "Clockwork Calm",
      description:
        "Mana Restore Multiplier +3.6% per rank, Energy Regen +3.6 per rank.",
      maxRank: 3,
      prerequisites: ["idler_5"],
    },
    {
      id: "idler_9",
      name: "Return Momentum",
      description: "Damage +2% per rank on login, Gold Income +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["idler_6"],
    },
    {
      id: "idler_10",
      name: "Fortune Reserve",
      description: "Spell Cooldown -2% per rank, Gold Income +3.2 per rank.",
      maxRank: 3,
      prerequisites: ["idler_7", "idler_8"],
    },
    {
      id: "idler_11",
      name: "Stillness Ward",
      description:
        "Reduce Incoming Damage by 4%, Defense +7.5. Defensive stabilizer.",
      maxRank: 1,
      prerequisites: ["idler_9"],
    },
    {
      id: "idler_12",
      name: "Perpetual Engine",
      description:
        "Offline Gold +10 per rank (20% if ranked), Energy Regen +6. Capstone.",
      maxRank: 1,
      prerequisites: ["idler_10", "idler_11"],
    },
    {
      id: "idler_13",
      name: "Reservoir Mind",
      description:
        "Mana Restore Multiplier +5% per rank, Energy Regen +3.6 per rank.",
      maxRank: 5,
      prerequisites: ["idler_12"],
    },
    {
      id: "idler_14",
      name: "Stored Friction",
      description: "All Damage +2.5% per rank after return windows.",
      maxRank: 5,
      prerequisites: ["idler_12"],
    },
    {
      id: "idler_15",
      name: "Soft Landing",
      description:
        "Reduce Incoming Damage by 1.5% per rank, Defense +2.8 per rank.",
      maxRank: 5,
      prerequisites: ["idler_13"],
    },
    {
      id: "idler_16",
      name: "Cooldown Float",
      description: "Reduce Spell Cooldown by 2.5% per rank.",
      maxRank: 5,
      prerequisites: ["idler_14"],
    },
    {
      id: "idler_17",
      name: "Deferred Crush",
      description: "All Damage +3% per rank after downtime conversions.",
      maxRank: 5,
      prerequisites: ["idler_15"],
    },
    {
      id: "idler_18",
      name: "Silent Compound",
      description:
        "Mana Restore Multiplier +5% per rank, Spell Cooldown -1.5% per rank.",
      maxRank: 3,
      prerequisites: ["idler_16"],
    },
    {
      id: "idler_19",
      name: "Wake Pressure",
      description: "All Damage +3.5% per rank, Gold Income +2.5 per rank.",
      maxRank: 5,
      prerequisites: ["idler_17"],
    },
    {
      id: "idler_20",
      name: "Patience Armor",
      description:
        "Reduce Incoming Damage by 2% per rank, All Damage +1.5% per rank.",
      maxRank: 3,
      prerequisites: ["idler_18", "idler_19"],
    },
    {
      id: "idler_21",
      name: "Compound Return",
      description: "Spell Cooldown -8%, Mana Restore +8%, Gold Income +8.",
      maxRank: 1,
      prerequisites: ["idler_19"],
    },
    {
      id: "idler_22",
      name: "Epoch Hoard",
      description:
        "All Damage +16%, Reduce Incoming Damage, Mana Restore +8%. Final capstone.",
      maxRank: 1,
      prerequisites: ["idler_20", "idler_21"],
    },
  ],
  classSpells: [
    {
      id: "idler_dividend",
      name: "Dividend Burst",
      description: "Cash out stored inactivity as a concentrated damage burst.",
      manaCost: 20,
      cooldownMs: 30000,
      requiredLevel: 10,
    },
    {
      id: "idler_timebank",
      name: "Timebank",
      description: "Withdraw a chunk of banked time to reset your pace.",
      manaCost: 32,
      cooldownMs: 36000,
      requiredLevel: 20,
    },
    {
      id: "idler_stored_force",
      name: "Stored Force",
      description: "Convert reserve value into a delayed but brutal impact.",
      manaCost: 36,
      cooldownMs: 33000,
      requiredLevel: 24,
    },
    {
      id: "idler_quietus_loop",
      name: "Quietus Loop",
      description: "Snap a silent loop of saved momentum around the enemy.",
      manaCost: 42,
      cooldownMs: 38000,
      requiredLevel: 28,
    },
    {
      id: "idler_delayed_crash",
      name: "Delayed Crash",
      description: "Cash in waiting time as a crashing deferred strike.",
      manaCost: 48,
      cooldownMs: 42000,
      requiredLevel: 32,
    },
    {
      id: "idler_reserve_flare",
      name: "Reserve Flare",
      description: "Ignite the reserve into a heavy single-target flare.",
      manaCost: 54,
      cooldownMs: 47000,
      requiredLevel: 36,
    },
    {
      id: "idler_echo_ledger",
      name: "Echo Ledger",
      description: "Cash out multiple past ticks in one crushing entry.",
      manaCost: 60,
      cooldownMs: 53000,
      requiredLevel: 40,
    },
    {
      id: "idler_patience_breaker",
      name: "Patience Breaker",
      description: "Shatter the calm with a huge return-on-waiting strike.",
      manaCost: 68,
      cooldownMs: 59000,
      requiredLevel: 44,
    },
    {
      id: "idler_long_wake",
      name: "Long Wake",
      description: "A long-stored wake breaks over the target all at once.",
      manaCost: 74,
      cooldownMs: 66000,
      requiredLevel: 48,
    },
    {
      id: "idler_epoch_cashout",
      name: "Epoch Cashout",
      description: "Spend an entire era of quiet advantage in one spell.",
      manaCost: 82,
      cooldownMs: 74000,
      requiredLevel: 52,
    },
  ],
};
