import type { CharacterClassDefinition } from "../types";

export const idlerClass: CharacterClassDefinition = {
  id: "idler",
  name: "Idler",
  summary: "Offline scaling and escalating daily check-in streak rewards.",
  fantasy: "A strategist who profits most from patience and consistency.",
  portraitAsset: "idler",
  nodes: [
    {
      id: "idler_1",
      name: "Long Arc",
      description: "Increase offline reward scaling.",
      maxRank: 5,
    },
    {
      id: "idler_2",
      name: "Silent Ledger",
      description: "Boost passive gold gain.",
      maxRank: 5,
      prerequisites: ["idler_1"],
    },
    {
      id: "idler_3",
      name: "Resting Edge",
      description: "Gain combat bonuses after being offline.",
      maxRank: 5,
      prerequisites: ["idler_1"],
    },
    {
      id: "idler_4",
      name: "Streak Keeper",
      description: "Improve daily streak reward growth.",
      maxRank: 5,
      prerequisites: ["idler_2"],
    },
    {
      id: "idler_5",
      name: "Quiet Reserve",
      description: "Increase stored mana while idle.",
      maxRank: 3,
      prerequisites: ["idler_2"],
    },
    {
      id: "idler_6",
      name: "Delayed Impact",
      description: "First active minutes after return are empowered.",
      maxRank: 5,
      prerequisites: ["idler_3"],
    },
    {
      id: "idler_7",
      name: "Patience Dividend",
      description: "Scale rewards by longer absences.",
      maxRank: 5,
      prerequisites: ["idler_4"],
    },
    {
      id: "idler_8",
      name: "Clockwork Calm",
      description: "Reduce decay in offline efficiency.",
      maxRank: 3,
      prerequisites: ["idler_5"],
    },
    {
      id: "idler_9",
      name: "Return Momentum",
      description: "Boost gains on login check-ins.",
      maxRank: 5,
      prerequisites: ["idler_6"],
    },
    {
      id: "idler_10",
      name: "Fortune Reserve",
      description: "Convert streak into temporary power.",
      maxRank: 3,
      prerequisites: ["idler_7", "idler_8"],
    },
    {
      id: "idler_11",
      name: "Stillness Ward",
      description: "Defensive stabilizer for idle cycles.",
      maxRank: 1,
      prerequisites: ["idler_9"],
    },
    {
      id: "idler_12",
      name: "Perpetual Engine",
      description: "Capstone for hybrid offline + streak economy.",
      maxRank: 1,
      prerequisites: ["idler_10", "idler_11"],
    },
  ],
  classSpells: [
    {
      id: "idler_dividend",
      name: "Dividend Burst",
      description: "Convert recent idle value into temporary combat power.",
      manaCost: 20,
      cooldownMs: 25000,
      requiredLevel: 10,
    },
    {
      id: "idler_timebank",
      name: "Timebank",
      description: "Bank current action for amplified next ticks.",
      manaCost: 32,
      cooldownMs: 30000,
      requiredLevel: 20,
    },
  ],
};
