import type { CharacterClassDefinition } from "../types";

export const sorceressClass: CharacterClassDefinition = {
  id: "sorceress",
  name: "Sorceress",
  summary: "Large spell toolkit with burst and stacking damage-over-time.",
  fantasy: "A master of arcane pressure, shields, and devastating cycles.",
  portraitAsset: "sorceress",
  nodes: [
    {
      id: "sorceress_1",
      name: "Arcane Capacity",
      description: "Increase mana efficiency.",
      maxRank: 5,
    },
    {
      id: "sorceress_2",
      name: "Spell Weaving",
      description: "Reduce global spell downtime.",
      maxRank: 5,
      prerequisites: ["sorceress_1"],
    },
    {
      id: "sorceress_3",
      name: "Ignition Thread",
      description: "Improve DOT potency.",
      maxRank: 5,
      prerequisites: ["sorceress_1"],
    },
    {
      id: "sorceress_4",
      name: "Aegis Orbit",
      description: "Gain shield on cast.",
      maxRank: 3,
      prerequisites: ["sorceress_2"],
    },
    {
      id: "sorceress_5",
      name: "Overcharge",
      description: "Increase burst spell scaling.",
      maxRank: 5,
      prerequisites: ["sorceress_2"],
    },
    {
      id: "sorceress_6",
      name: "Kindling Echo",
      description: "DOT ticks can spread.",
      maxRank: 3,
      prerequisites: ["sorceress_3"],
    },
    {
      id: "sorceress_7",
      name: "Temporal Focus",
      description: "Increase cast speed during chain windows.",
      maxRank: 5,
      prerequisites: ["sorceress_4"],
    },
    {
      id: "sorceress_8",
      name: "Runic Recovery",
      description: "Restore mana while protected.",
      maxRank: 3,
      prerequisites: ["sorceress_5"],
    },
    {
      id: "sorceress_9",
      name: "Storm Sigil",
      description: "Add extra impact to arcane spells.",
      maxRank: 5,
      prerequisites: ["sorceress_6"],
    },
    {
      id: "sorceress_10",
      name: "Fate Detonation",
      description: "Consume DOT stacks for burst.",
      maxRank: 3,
      prerequisites: ["sorceress_7", "sorceress_8"],
    },
    {
      id: "sorceress_11",
      name: "Mirror Veil",
      description: "Emergency survivability layer.",
      maxRank: 1,
      prerequisites: ["sorceress_9"],
    },
    {
      id: "sorceress_12",
      name: "Astral Dominion",
      description: "Capstone for full spell-cycle dominance.",
      maxRank: 1,
      prerequisites: ["sorceress_10", "sorceress_11"],
    },
  ],
  classSpells: [
    {
      id: "sorceress_nova",
      name: "Star Nova",
      description: "Huge arcane burst around the target.",
      manaCost: 45,
      cooldownMs: 20000,
      requiredLevel: 10,
    },
    {
      id: "sorceress_hexfire",
      name: "Hexfire",
      description: "Fast-ticking stacking DOT curse.",
      manaCost: 30,
      cooldownMs: 9000,
      requiredLevel: 20,
    },
  ],
};
