import type { CharacterClassDefinition } from "../types";

export const sorceressClass: CharacterClassDefinition = {
  id: "sorceress",
  name: "Sorceress",
  summary: "Large spell toolkit with burst and stacking damage-over-time.",
  fantasy: "A master of arcane pressure, shields, and devastating cycles.",
  portraitAsset: "sorceress",
  nodes: [
    {
      id: "sorceress_1",
      name: "Arcane Capacity",
      description:
        "Reduce Spell Mana Cost by 2.5% per rank, Energy Regen +5.5 per rank.",
      maxRank: 5,
    },
    {
      id: "sorceress_2",
      name: "Spell Weaving",
      description:
        "Reduce Spell Cooldown by 3% per rank, Intelligence +2.8 per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_1"],
    },
    {
      id: "sorceress_3",
      name: "Ignition Thread",
      description: "Spell Damage +5% per rank, Intelligence +3.2 per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_1"],
    },
    {
      id: "sorceress_4",
      name: "Aegis Orbit",
      description: "Increase Healing by 3% per rank, Defense +2.2 per rank.",
      maxRank: 3,
      prerequisites: ["sorceress_2"],
    },
    {
      id: "sorceress_5",
      name: "Overcharge",
      description: "Spell Damage +4.5% per rank, Attack +2.6 per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_2"],
    },
    {
      id: "sorceress_6",
      name: "Kindling Echo",
      description: "Crit Chance +1.5% per rank.",
      maxRank: 3,
      prerequisites: ["sorceress_3"],
    },
    {
      id: "sorceress_7",
      name: "Temporal Focus",
      description:
        "Increase APS Multiplier by 2.5% per rank, Agility +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_4"],
    },
    {
      id: "sorceress_8",
      name: "Runic Recovery",
      description:
        "Mana Restore Multiplier +5% per rank, Energy Regen +4.8 per rank.",
      maxRank: 3,
      prerequisites: ["sorceress_5"],
    },
    {
      id: "sorceress_9",
      name: "Storm Sigil",
      description: "Spell Damage +4% per rank, Intelligence +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_6"],
    },
    {
      id: "sorceress_10",
      name: "Fate Detonation",
      description: "Spell Damage +6% per rank, Crit Chance +2% per rank.",
      maxRank: 3,
      prerequisites: ["sorceress_7", "sorceress_8"],
    },
    {
      id: "sorceress_11",
      name: "Mirror Veil",
      description:
        "Survive lethal hit with 28% chance and heal to 18% HP. Defense +8.",
      maxRank: 1,
      prerequisites: ["sorceress_9"],
    },
    {
      id: "sorceress_12",
      name: "Astral Dominion",
      description: "Spell Damage +22%, Intelligence +14, Attack +6. Capstone.",
      maxRank: 1,
      prerequisites: ["sorceress_10", "sorceress_11"],
    },
    {
      id: "sorceress_13",
      name: "Mana Prism",
      description:
        "Mana Restore Multiplier +6% per rank, Energy Regen +4.5 per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_12"],
    },
    {
      id: "sorceress_14",
      name: "Cataclysm Thread",
      description: "Spell Damage +5% per rank, Intelligence +3 per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_12"],
    },
    {
      id: "sorceress_15",
      name: "Clockburn",
      description: "Reduce Spell Cooldown by 2.5% per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_13"],
    },
    {
      id: "sorceress_16",
      name: "Glass Constellation",
      description: "Crit Chance +1.8% per rank, Spell Damage +2% per rank.",
      maxRank: 3,
      prerequisites: ["sorceress_14"],
    },
    {
      id: "sorceress_17",
      name: "Spell Siphon",
      description: "Reduce Spell Mana Cost by 3% per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_15"],
    },
    {
      id: "sorceress_18",
      name: "Aether Bloom",
      description: "Healing +5% per rank, Spell Damage +2.5% per rank.",
      maxRank: 3,
      prerequisites: ["sorceress_16"],
    },
    {
      id: "sorceress_19",
      name: "Eventide Spiral",
      description: "APS Multiplier +3.5% per rank, Intelligence +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["sorceress_17"],
    },
    {
      id: "sorceress_20",
      name: "Rift Choir",
      description:
        "Spell Damage +7% per rank, Mana Restore Multiplier +4% per rank.",
      maxRank: 3,
      prerequisites: ["sorceress_18", "sorceress_19"],
    },
    {
      id: "sorceress_21",
      name: "Void Crown",
      description: "Spell Damage +8%, Spell Cooldown -8%, Intelligence +10.",
      maxRank: 1,
      prerequisites: ["sorceress_19"],
    },
    {
      id: "sorceress_22",
      name: "Nightstar Queen",
      description:
        "Spell Damage +20%, Crit Chance +3%, Mana Restore +8%. Final capstone.",
      maxRank: 1,
      prerequisites: ["sorceress_20", "sorceress_21"],
    },
  ],
  classSpells: [
    {
      id: "sorceress_nova",
      name: "Star Nova",
      description: "Collapse a blazing star directly into the target.",
      manaCost: 45,
      cooldownMs: 24000,
      requiredLevel: 10,
    },
    {
      id: "sorceress_hexfire",
      name: "Hexfire",
      description: "Brand the enemy with a stacking infernal curse.",
      manaCost: 30,
      cooldownMs: 14000,
      requiredLevel: 20,
    },
    {
      id: "sorceress_comet_spear",
      name: "Comet Spear",
      description: "Drive an incandescent comet lance through the enemy.",
      manaCost: 42,
      cooldownMs: 26000,
      requiredLevel: 24,
    },
    {
      id: "sorceress_void_pulse",
      name: "Void Pulse",
      description: "A compressing pulse of dark arcana with violent payoff.",
      manaCost: 48,
      cooldownMs: 30000,
      requiredLevel: 28,
    },
    {
      id: "sorceress_crown_of_cinders",
      name: "Crown of Cinders",
      description: "Rain cinders from above in a concentrated execution burst.",
      manaCost: 54,
      cooldownMs: 34000,
      requiredLevel: 32,
    },
    {
      id: "sorceress_prism_collapse",
      name: "Prism Collapse",
      description: "Shatter layered magic into a single annihilating beam.",
      manaCost: 60,
      cooldownMs: 39000,
      requiredLevel: 36,
    },
    {
      id: "sorceress_astral_scythe",
      name: "Astral Scythe",
      description: "Scythe the target with a crescent of stellar force.",
      manaCost: 66,
      cooldownMs: 45000,
      requiredLevel: 40,
    },
    {
      id: "sorceress_rift_torrent",
      name: "Rift Torrent",
      description:
        "Open a short-lived rift that unloads compressed arcane ruin.",
      manaCost: 72,
      cooldownMs: 50000,
      requiredLevel: 44,
    },
    {
      id: "sorceress_supernova_sigil",
      name: "Supernova Sigil",
      description: "Detonate an engraved sigil in a singularity-scale blast.",
      manaCost: 80,
      cooldownMs: 58000,
      requiredLevel: 48,
    },
    {
      id: "sorceress_eclipse_verdict",
      name: "Eclipse Verdict",
      description: "Pass final judgment in a catastrophic arcane eclipse.",
      manaCost: 88,
      cooldownMs: 66000,
      requiredLevel: 52,
    },
  ],
};
