import type { CharacterClassDefinition } from "../types";

export const tamerClass: CharacterClassDefinition = {
  id: "tamer",
  name: "Tamer",
  summary:
    "Massive pet amplification with passive and active companion support.",
  fantasy: "A bond-driven fighter whose companions become the main weapon.",
  portraitAsset: "tamer",
  nodes: [
    {
      id: "tamer_1",
      name: "Bond Strength",
      description: "Pet Damage +7% per rank, Pet Strength +5.5 per rank.",
      maxRank: 5,
    },
    {
      id: "tamer_2",
      name: "Companion Instinct",
      description: "Pet Proc Chance +3% per rank, Agility +2.8 per rank.",
      maxRank: 5,
      prerequisites: ["tamer_1"],
    },
    {
      id: "tamer_3",
      name: "Shared Resolve",
      description:
        "Reduce Incoming Damage by 2% per rank, Defense +2.5 per rank.",
      maxRank: 3,
      prerequisites: ["tamer_1"],
    },
    {
      id: "tamer_synergy",
      name: "Pack Focus",
      description:
        "Unlock Active Skill Pack Focus: your next Tamer spell deals 5x damage.",
      maxRank: 1,
      prerequisites: ["tamer_2"],
    },
    {
      id: "tamer_4",
      name: "Feral Training",
      description: "Crit Chance +1.4% per rank, Pet crit bonus.",
      maxRank: 5,
      prerequisites: ["tamer_2"],
    },
    {
      id: "tamer_5",
      name: "Pack Tactics",
      description: "All Damage +3% per rank, Attack +2.8 per rank.",
      maxRank: 5,
      prerequisites: ["tamer_2"],
    },
    {
      id: "tamer_6",
      name: "Echo Command",
      description:
        "Pet Proc Damage Multiplier +8% per rank, Pet Strength +4.2 per rank.",
      maxRank: 3,
      prerequisites: ["tamer_3"],
    },
    {
      id: "tamer_7",
      name: "Predator Pace",
      description: "Pet Damage +4.5% per rank, Agility +2.6 per rank.",
      maxRank: 5,
      prerequisites: ["tamer_4"],
    },
    {
      id: "tamer_8",
      name: "Wild Bulwark",
      description:
        "Reduce Incoming Damage by 2.5% per rank, Defense +2.6 per rank.",
      maxRank: 3,
      prerequisites: ["tamer_5"],
    },
    {
      id: "tamer_9",
      name: "Alpha Signal",
      description: "Pet Damage +6% per rank, Pet Strength +4 per rank.",
      maxRank: 5,
      prerequisites: ["tamer_6"],
    },
    {
      id: "tamer_10",
      name: "Companion Frenzy",
      description: "Pet Proc Chance +3% per rank, Attack +3.5 per rank.",
      maxRank: 3,
      prerequisites: ["tamer_7", "tamer_8"],
    },
    {
      id: "tamer_11",
      name: "Guardian Bond",
      description:
        "Survive lethal hit with 32% chance and heal to 18% HP. HP +10.5.",
      maxRank: 1,
      prerequisites: ["tamer_9"],
    },
    {
      id: "tamer_12",
      name: "Primal Concord",
      description: "Pet Damage +20%, Pet Strength +10, Attack +8. Capstone.",
      maxRank: 1,
      prerequisites: ["tamer_10", "tamer_11"],
    },
    {
      id: "tamer_13",
      name: "Fang Oath",
      description: "Pet Damage +6% per rank, Pet Strength +3.8 per rank.",
      maxRank: 5,
      prerequisites: ["tamer_12"],
    },
    {
      id: "tamer_14",
      name: "Signal Bark",
      description: "Pet Proc Chance +2.5% per rank, Agility +2.4 per rank.",
      maxRank: 5,
      prerequisites: ["tamer_12"],
    },
    {
      id: "tamer_15",
      name: "Rending Pack",
      description:
        "Pet Proc Damage Multiplier +10% per rank, Attack +2.4 per rank.",
      maxRank: 3,
      prerequisites: ["tamer_13"],
    },
    {
      id: "tamer_16",
      name: "Lead Whistle",
      description: "All Damage +2% per rank, Pet Strength +2.8 per rank.",
      maxRank: 5,
      prerequisites: ["tamer_14"],
    },
    {
      id: "tamer_17",
      name: "Predator's Sight",
      description: "Crit Chance +1.2% per rank, Pet Damage +2% per rank.",
      maxRank: 5,
      prerequisites: ["tamer_15"],
    },
    {
      id: "tamer_18",
      name: "Den Wall",
      description:
        "Reduce Incoming Damage by 2% per rank, Defense +2.6 per rank.",
      maxRank: 3,
      prerequisites: ["tamer_16"],
    },
    {
      id: "tamer_19",
      name: "Alpha Relay",
      description: "Pet Damage +7% per rank, Pet Proc Chance +1% per rank.",
      maxRank: 5,
      prerequisites: ["tamer_17"],
    },
    {
      id: "tamer_20",
      name: "Packbreaker",
      description:
        "Pet Proc Damage Multiplier +12% per rank, All Damage +1.5% per rank.",
      maxRank: 3,
      prerequisites: ["tamer_18", "tamer_19"],
    },
    {
      id: "tamer_21",
      name: "Sovereign Leash",
      description: "Pet Damage +10%, Reduce Incoming Damage, HP +14.",
      maxRank: 1,
      prerequisites: ["tamer_19"],
    },
    {
      id: "tamer_22",
      name: "Wild Hunt Pact",
      description:
        "Pet Damage +20%, Pet Proc Damage +15%, Crit Chance +3%. Final capstone.",
      maxRank: 1,
      prerequisites: ["tamer_20", "tamer_21"],
    },
  ],
  classSpells: [
    {
      id: "tamer_pack_focus",
      name: "Pack Focus",
      description:
        "Signal a perfect opening so your next Tamer spell surges with amplified pack synergy.",
      manaCost: 22,
      cooldownMs: 30000,
      requiredLevel: 12,
    },
    {
      id: "tamer_pack_howl",
      name: "Pack Howl",
      description: "Call the pack into a savage coordinated strike.",
      manaCost: 30,
      cooldownMs: 20000,
      requiredLevel: 10,
    },
    {
      id: "tamer_beast_sync",
      name: "Beast Sync",
      description: "Force perfect synchronization for a punishing double hit.",
      manaCost: 40,
      cooldownMs: 28000,
      requiredLevel: 20,
    },
    {
      id: "tamer_alpha_pounce",
      name: "Alpha Pounce",
      description: "The alpha lunges first and the whole pack follows through.",
      manaCost: 38,
      cooldownMs: 24000,
      requiredLevel: 24,
    },
    {
      id: "tamer_fang_relay",
      name: "Fang Relay",
      description: "Chain a sequence of biting companion strikes.",
      manaCost: 46,
      cooldownMs: 29000,
      requiredLevel: 28,
    },
    {
      id: "tamer_den_stampede",
      name: "Den Stampede",
      description: "Crash the enemy under a full companion rush.",
      manaCost: 52,
      cooldownMs: 34000,
      requiredLevel: 32,
    },
    {
      id: "tamer_spirit_lash",
      name: "Spirit Lash",
      description: "A spectral companion lashes forward with brutal force.",
      manaCost: 58,
      cooldownMs: 39000,
      requiredLevel: 36,
    },
    {
      id: "tamer_packbreaker",
      name: "Packbreaker",
      description: "A heavy synchronized maul meant to break elite prey.",
      manaCost: 64,
      cooldownMs: 45000,
      requiredLevel: 40,
    },
    {
      id: "tamer_sovereign_call",
      name: "Sovereign Call",
      description: "Call the strongest bond forward for a decisive assault.",
      manaCost: 70,
      cooldownMs: 51000,
      requiredLevel: 44,
    },
    {
      id: "tamer_bestial_eclipse",
      name: "Bestial Eclipse",
      description: "Let the pack blot out the fight in one overwhelming cast.",
      manaCost: 76,
      cooldownMs: 58000,
      requiredLevel: 48,
    },
    {
      id: "tamer_wild_hunt",
      name: "Wild Hunt",
      description:
        "Loose the full hunt and end the fight in a coordinated kill.",
      manaCost: 84,
      cooldownMs: 66000,
      requiredLevel: 52,
    },
  ],
};
